[2024-12-19T17:45:21.569-0800] {processor.py:186} INFO - Started process (PID=68259) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-19T17:45:21.570-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-19T17:45:21.572-0800] {logging_mixin.py:190} INFO - [2024-12-19T17:45:21.572-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-19T17:45:21.598-0800] {logging_mixin.py:190} INFO - [2024-12-19T17:45:21.598-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-19T17:45:21.599-0800] {logging_mixin.py:190} INFO - [2024-12-19T17:45:21.599-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-19T17:45:21.599-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-19T17:45:21.669-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
[2024-12-19T21:05:06.113-0800] {processor.py:186} INFO - Started process (PID=68606) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-19T21:05:06.130-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-19T21:05:06.137-0800] {logging_mixin.py:190} INFO - [2024-12-19T21:05:06.136-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-19T21:05:06.442-0800] {logging_mixin.py:190} INFO - [2024-12-19T21:05:06.438-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-19T21:05:06.445-0800] {logging_mixin.py:190} INFO - [2024-12-19T21:05:06.444-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-19T21:05:06.446-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-19T21:05:07.118-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 1.057 seconds
[2024-12-19T23:52:03.931-0800] {processor.py:186} INFO - Started process (PID=68805) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-19T23:52:03.934-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-19T23:52:03.958-0800] {logging_mixin.py:190} INFO - [2024-12-19T23:52:03.957-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-19T23:52:03.993-0800] {logging_mixin.py:190} INFO - [2024-12-19T23:52:03.992-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-19T23:52:03.993-0800] {logging_mixin.py:190} INFO - [2024-12-19T23:52:03.993-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-19T23:52:03.993-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-19T23:52:04.062-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.138 seconds
[2024-12-20T08:20:08.205-0800] {processor.py:186} INFO - Started process (PID=69039) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T08:20:08.207-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T08:20:08.209-0800] {logging_mixin.py:190} INFO - [2024-12-20T08:20:08.208-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T08:20:08.242-0800] {logging_mixin.py:190} INFO - [2024-12-20T08:20:08.242-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T08:20:08.243-0800] {logging_mixin.py:190} INFO - [2024-12-20T08:20:08.243-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T08:20:08.243-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T08:20:08.322-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.122 seconds
[2024-12-20T08:35:37.158-0800] {processor.py:186} INFO - Started process (PID=69251) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T08:35:37.160-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T08:35:37.162-0800] {logging_mixin.py:190} INFO - [2024-12-20T08:35:37.161-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T08:35:37.195-0800] {logging_mixin.py:190} INFO - [2024-12-20T08:35:37.194-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T08:35:37.195-0800] {logging_mixin.py:190} INFO - [2024-12-20T08:35:37.195-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T08:35:37.195-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T08:35:37.265-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2024-12-20T09:39:59.782-0800] {processor.py:186} INFO - Started process (PID=69474) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T09:39:59.785-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T09:39:59.786-0800] {logging_mixin.py:190} INFO - [2024-12-20T09:39:59.786-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T09:39:59.825-0800] {logging_mixin.py:190} INFO - [2024-12-20T09:39:59.823-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T09:39:59.825-0800] {logging_mixin.py:190} INFO - [2024-12-20T09:39:59.825-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T09:39:59.826-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T09:39:59.905-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.129 seconds
[2024-12-20T10:11:07.979-0800] {processor.py:186} INFO - Started process (PID=69685) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:11:07.982-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:11:07.984-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:11:07.983-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:11:08.018-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:11:08.018-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:11:08.019-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:11:08.019-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:11:08.019-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:11:08.096-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.124 seconds
[2024-12-20T10:14:49.647-0800] {processor.py:186} INFO - Started process (PID=69875) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:14:49.650-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:14:49.651-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:14:49.651-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:14:49.688-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:14:49.687-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:14:49.688-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:14:49.688-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:14:49.689-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:14:49.770-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.132 seconds
[2024-12-20T10:17:59.468-0800] {processor.py:186} INFO - Started process (PID=70049) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:17:59.470-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:17:59.472-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:17:59.471-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:17:59.509-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:17:59.509-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:17:59.509-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:17:59.509-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:17:59.510-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:17:59.593-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.133 seconds
[2024-12-20T10:21:02.272-0800] {processor.py:186} INFO - Started process (PID=70212) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:21:02.275-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:21:02.276-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:21:02.276-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:21:02.311-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:21:02.310-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:21:02.312-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:21:02.312-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:21:02.312-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:21:02.387-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.123 seconds
[2024-12-20T10:24:02.498-0800] {processor.py:186} INFO - Started process (PID=70382) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:24:02.500-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:24:02.502-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:24:02.502-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:24:02.531-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:24:02.531-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:24:02.531-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:24:02.531-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:24:02.532-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:24:02.607-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2024-12-20T10:27:01.665-0800] {processor.py:186} INFO - Started process (PID=70540) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:27:01.668-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:27:01.670-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:27:01.669-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:27:01.705-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:27:01.704-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:27:01.705-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:27:01.705-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:27:01.705-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:27:01.791-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.132 seconds
[2024-12-20T10:30:05.334-0800] {processor.py:186} INFO - Started process (PID=70692) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:30:05.336-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:30:05.338-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:30:05.337-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:30:05.372-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:30:05.371-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:30:05.373-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:30:05.372-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:30:05.373-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:30:05.453-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.126 seconds
[2024-12-20T10:33:12.323-0800] {processor.py:186} INFO - Started process (PID=70869) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:33:12.327-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:33:12.328-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:33:12.328-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:33:12.363-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:33:12.362-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:33:12.364-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:33:12.363-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:33:12.364-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:33:12.442-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.124 seconds
[2024-12-20T10:36:22.076-0800] {processor.py:186} INFO - Started process (PID=71033) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:36:22.078-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:36:22.079-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:36:22.079-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:36:22.116-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:36:22.116-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:36:22.117-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:36:22.116-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:36:22.117-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:36:22.209-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.138 seconds
[2024-12-20T10:39:38.437-0800] {processor.py:186} INFO - Started process (PID=71205) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:39:38.440-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:39:38.441-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:39:38.441-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:39:38.474-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:39:38.473-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:39:38.474-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:39:38.474-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:39:38.474-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:39:38.556-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.124 seconds
[2024-12-20T10:42:51.587-0800] {processor.py:186} INFO - Started process (PID=71363) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:42:51.589-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:42:51.590-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:42:51.590-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:42:51.627-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:42:51.627-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:42:51.628-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:42:51.628-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:42:51.628-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:42:51.711-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.131 seconds
[2024-12-20T10:46:02.269-0800] {processor.py:186} INFO - Started process (PID=71510) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:46:02.271-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:46:02.273-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:46:02.273-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:46:02.309-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:46:02.309-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:46:02.310-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:46:02.310-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:46:02.310-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:46:02.402-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.142 seconds
[2024-12-20T10:49:16.752-0800] {processor.py:186} INFO - Started process (PID=71657) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:49:16.755-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:49:16.756-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:49:16.756-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:49:16.789-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:49:16.788-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:49:16.789-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:49:16.789-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:49:16.789-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:49:16.873-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.128 seconds
[2024-12-20T10:52:34.818-0800] {processor.py:186} INFO - Started process (PID=71819) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:52:34.821-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:52:34.822-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:52:34.822-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:52:34.857-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:52:34.856-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:52:34.857-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:52:34.857-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:52:34.858-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:52:34.966-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.158 seconds
[2024-12-20T10:55:55.787-0800] {processor.py:186} INFO - Started process (PID=71967) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:55:55.789-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:55:55.791-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:55:55.791-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:55:55.829-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:55:55.828-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:55:55.829-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:55:55.829-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:55:55.829-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:55:55.912-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.134 seconds
[2024-12-20T10:59:03.971-0800] {processor.py:186} INFO - Started process (PID=72114) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:59:03.973-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T10:59:03.975-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:59:03.975-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:59:04.009-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:59:04.008-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T10:59:04.009-0800] {logging_mixin.py:190} INFO - [2024-12-20T10:59:04.009-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T10:59:04.009-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T10:59:04.092-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.126 seconds
[2024-12-20T11:02:10.954-0800] {processor.py:186} INFO - Started process (PID=72258) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:02:10.956-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:02:10.958-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:02:10.957-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:02:10.994-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:02:10.993-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:02:10.994-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:02:10.994-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:02:10.994-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:02:11.076-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.131 seconds
[2024-12-20T11:05:31.296-0800] {processor.py:186} INFO - Started process (PID=72425) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:05:31.298-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:05:31.299-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:05:31.299-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:05:31.338-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:05:31.338-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:05:31.339-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:05:31.339-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:05:31.339-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:05:31.423-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.133 seconds
[2024-12-20T11:08:42.479-0800] {processor.py:186} INFO - Started process (PID=72573) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:08:42.481-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:08:42.482-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:08:42.482-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:08:42.521-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:08:42.520-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:08:42.521-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:08:42.521-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:08:42.521-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:08:42.606-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.134 seconds
[2024-12-20T11:11:57.599-0800] {processor.py:186} INFO - Started process (PID=72738) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:11:57.602-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:11:57.604-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:11:57.603-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:11:57.638-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:11:57.637-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:11:57.638-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:11:57.638-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:11:57.639-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:11:57.725-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.132 seconds
[2024-12-20T11:15:11.876-0800] {processor.py:186} INFO - Started process (PID=72891) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:15:11.878-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:15:11.880-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:15:11.880-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:15:11.913-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:15:11.912-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:15:11.913-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:15:11.913-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:15:11.914-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:15:11.990-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.121 seconds
[2024-12-20T11:18:18.036-0800] {processor.py:186} INFO - Started process (PID=73053) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:18:18.039-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:18:18.041-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:18:18.041-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:18:18.075-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:18:18.074-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:18:18.076-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:18:18.075-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:18:18.076-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:18:18.147-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2024-12-20T11:21:22.134-0800] {processor.py:186} INFO - Started process (PID=73211) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:21:22.137-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:21:22.139-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:21:22.138-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:21:22.175-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:21:22.174-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:21:22.176-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:21:22.176-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:21:22.176-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:21:22.258-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.131 seconds
[2024-12-20T11:24:26.288-0800] {processor.py:186} INFO - Started process (PID=73379) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:24:26.291-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:24:26.293-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:24:26.292-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:24:26.322-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:24:26.321-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:24:26.322-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:24:26.322-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:24:26.322-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:24:26.392-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
[2024-12-20T11:27:27.649-0800] {processor.py:186} INFO - Started process (PID=73536) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:27:27.651-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:27:27.653-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:27:27.653-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:27:27.685-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:27:27.684-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:27:27.685-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:27:27.685-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:27:27.686-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:27:27.758-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2024-12-20T11:30:27.320-0800] {processor.py:186} INFO - Started process (PID=73683) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:30:27.323-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:30:27.324-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:30:27.324-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:30:27.358-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:30:27.357-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:30:27.359-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:30:27.358-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:30:27.359-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:30:27.430-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2024-12-20T11:33:29.762-0800] {processor.py:186} INFO - Started process (PID=73841) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:33:29.764-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:33:29.765-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:33:29.765-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:33:29.797-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:33:29.796-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:33:29.798-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:33:29.797-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:33:29.798-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:33:29.871-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2024-12-20T11:36:35.759-0800] {processor.py:186} INFO - Started process (PID=73989) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:36:35.762-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:36:35.763-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:36:35.763-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:36:35.798-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:36:35.797-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:36:35.799-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:36:35.799-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:36:35.799-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:36:35.874-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.120 seconds
[2024-12-20T11:55:01.015-0800] {processor.py:186} INFO - Started process (PID=74137) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:55:01.019-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:55:01.021-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:55:01.021-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:55:01.068-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:55:01.067-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:55:01.069-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:55:01.068-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:55:01.069-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:55:01.238-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.227 seconds
[2024-12-20T11:58:15.318-0800] {processor.py:186} INFO - Started process (PID=74320) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:58:15.322-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T11:58:15.323-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:58:15.323-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:58:15.364-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:58:15.363-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T11:58:15.364-0800] {logging_mixin.py:190} INFO - [2024-12-20T11:58:15.364-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T11:58:15.364-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T11:58:15.447-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2024-12-20T12:02:23.790-0800] {processor.py:186} INFO - Started process (PID=74491) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T12:02:23.794-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T12:02:23.797-0800] {logging_mixin.py:190} INFO - [2024-12-20T12:02:23.796-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T12:02:23.865-0800] {logging_mixin.py:190} INFO - [2024-12-20T12:02:23.864-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T12:02:23.866-0800] {logging_mixin.py:190} INFO - [2024-12-20T12:02:23.865-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T12:02:23.866-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T12:02:24.042-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.267 seconds
[2024-12-20T12:07:35.998-0800] {processor.py:186} INFO - Started process (PID=74711) to work on /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T12:07:36.001-0800] {processor.py:914} INFO - Processing file /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-12-20T12:07:36.004-0800] {logging_mixin.py:190} INFO - [2024-12-20T12:07:36.003-0800] {dagbag.py:588} INFO - Filling up the DagBag from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T12:07:36.070-0800] {logging_mixin.py:190} INFO - [2024-12-20T12:07:36.069-0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-12-20T12:07:36.071-0800] {logging_mixin.py:190} INFO - [2024-12-20T12:07:36.071-0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-12-20T12:07:36.072-0800] {processor.py:927} WARNING - No viable dags retrieved from /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-12-20T12:07:36.246-0800] {processor.py:208} INFO - Processing /Users/rishukhurana/anaconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.264 seconds
